-- MySQL Script generated by MySQL Workbench
-- Thu Oct 30 20:12:56 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema proyectobd
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema proyectobd
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `proyectobd` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ;
USE `proyectobd` ;

-- -----------------------------------------------------
-- Table `proyectobd`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyectobd`.`usuario` (
  `id` VARCHAR(20) NOT NULL,
  `clave` VARCHAR(45) NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `tipo` ENUM('MEDICO', 'FARMACEUTA', 'ADMIN') NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `proyectobd`.`paciente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyectobd`.`paciente` (
  `id` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `fecha_nacimiento` DATE NOT NULL,
  `telefono` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `proyectobd`.`receta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyectobd`.`receta` (
  `codigo` VARCHAR(20) NOT NULL,
  `id_paciente` INT NOT NULL,
  `fecha_confeccion` DATE NOT NULL,
  `fecha_retiro` DATE NOT NULL,
  `estado` ENUM('CONFECCIONADA', 'PROCESO', 'LISTA', 'ENTREGADA') NOT NULL DEFAULT 'CONFECCIONADA',
  `id_farmaceuta_proceso` VARCHAR(20) NULL DEFAULT NULL,
  `id_farmaceuta_lista` VARCHAR(20) NULL DEFAULT NULL,
  `id_farmaceuta_entregada` VARCHAR(20) NULL DEFAULT NULL,
  PRIMARY KEY (`codigo`),
  INDEX `id_medico` (`id_farmaceuta_proceso` ASC) VISIBLE,
  INDEX `id_paciente` (`id_paciente` ASC) VISIBLE,
  INDEX `fk_receta_usuario1_idx` (`id_farmaceuta_lista` ASC) VISIBLE,
  INDEX `fk_receta_usuario2_idx` (`id_farmaceuta_entregada` ASC) VISIBLE,
  CONSTRAINT `fk_receta_usuario1`
    FOREIGN KEY (`id_farmaceuta_lista`)
    REFERENCES `proyectobd`.`usuario` (`id`),
  CONSTRAINT `fk_receta_usuario2`
    FOREIGN KEY (`id_farmaceuta_entregada`)
    REFERENCES `proyectobd`.`usuario` (`id`),
  CONSTRAINT `receta_ibfk_1`
    FOREIGN KEY (`id_farmaceuta_proceso`)
    REFERENCES `proyectobd`.`usuario` (`id`),
  CONSTRAINT `receta_ibfk_2`
    FOREIGN KEY (`id_paciente`)
    REFERENCES `proyectobd`.`paciente` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `proyectobd`.`medicamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyectobd`.`medicamento` (
  `codigo` VARCHAR(20) NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `presentacion` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`codigo`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `proyectobd`.`indicacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyectobd`.`indicacion` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `receta_codigo` VARCHAR(20) NOT NULL,
  `medicamento_codigo` VARCHAR(20) NOT NULL,
  `cantidad` INT NOT NULL,
  `indicaciones` VARCHAR(100) NULL DEFAULT NULL,
  `duracion_dias` INT NOT NULL,
  INDEX `medicamento_codigo` (`medicamento_codigo` ASC) VISIBLE,
  INDEX `fk_indicacion_receta1_idx` (`receta_codigo` ASC) VISIBLE,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_indicacion_receta1`
    FOREIGN KEY (`receta_codigo`)
    REFERENCES `proyectobd`.`receta` (`codigo`),
  CONSTRAINT `receta_detalle_ibfk_2`
    FOREIGN KEY (`medicamento_codigo`)
    REFERENCES `proyectobd`.`medicamento` (`codigo`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `proyectobd`.`medico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyectobd`.`medico` (
  `usuario_id` VARCHAR(20) NOT NULL,
  `especialidad` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`usuario_id`),
  CONSTRAINT `fk_medico_usuario1`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `proyectobd`.`usuario` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


-- -----------------------------------------------------
-- Table `proyectobd`.`mensaje`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `proyectobd`.`mensaje` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `remitente` VARCHAR(20) NULL DEFAULT NULL,
  `destinatario` VARCHAR(20) NULL DEFAULT NULL,
  `texto` TEXT NULL DEFAULT NULL,
  `fecha_envio` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_unicode_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
